/** ACTION TYPES FOR OVERLAY LOADING */
export const START_OVERLAY_LOADING = "START_OVERLAY_LOADING";
export const STOP_OVERLAY_LOADING = "STOP_OVERLAY_LOADING";



/** ACTION TYPES FOR AUTH */
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const ACTIVITY_FAIL = "ACTIVITY_FAIL";
export const AUTH_EXIST_FAIL = "AUTH_EXIST_FAIL";
export const AUTH_VALID_FAIL = "AUTH_VALID_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";


/** ACTION TYPES FOR HOME */
export const SUBCRIBE_SUCCESS = "SUBCRIBE_SUCCESS";
export const GET_HOMEPLACE= "GET_HOMEPLACE";
export const GET_ALL_CITY="GET_ALL_CITY";
export const LOGOUT = "LOGOUT"


//TODO SEARCH MODULE
export const GET_SEARCH_RESULT = "GET_SEARCH_RESULT";
export const LOADER_SET = 'loader/SET'
